# Generated by Django 5.0.4 on 2024-05-01 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_add_expense_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_expense',
            name='user',
        ),
    ]
